language: rust
rust:
  - stable
  - nightly-2019-02-08
cache: cargo
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        rustup toolchain add nightly-2019-02-08
        rustup component add --toolchain nightly-2019-02-08 clippy
      else
        rustup component add clippy
      fi
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --release
