language: rust
rust:
  - stable
cache: cargo
before_script:
  - cargo install --force cargo-audit
  - cargo generate-lockfile
  - rustup component add clippy
script:
  - cargo audit
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --release
