language: rust
rust:
  - stable
  - nightly
cache: cargo
  before_script:
    - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --release
